### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by benzenesulfonic-acid** [immstudios/installers#1]
I want  to run install.kaltura.sh but I meet a error. os ubuntu 16.04LTS amd64.

/tmp/install.kaltura.sh/nginx-vod-module/vod/filters/audio_decoder.c:22:2: error: ‘avcodec_register_all’ is deprecated [-Werror=deprecated-declarations]
  avcodec_register_all();
  ^
In file included from /tmp/install.kaltura.sh/nginx-vod-module/vod/filters/../input/../common.h:110:0,
                 from /tmp/install.kaltura.sh/nginx-vod-module/vod/filters/../input/read_cache.h:5,
                 from /tmp/install.kaltura.sh/nginx-vod-module/vod/filters/../input/frames_source.h:5,
                 from /tmp/install.kaltura.sh/nginx-vod-module/vod/filters/../media_format.h:5,
                 from /tmp/install.kaltura.sh/nginx-vod-module/vod/filters/audio_decoder.h:5,
                 from /tmp/install.kaltura.sh/nginx-vod-module/vod/filters/audio_decoder.c:1:
/usr/local/include/libavcodec/avcodec.h:4086:6: note: declared here
 void avcodec_register_all(void);
      ^
cc1: all warnings being treated as errors
objs/Makefile:1762: recipe for target 'objs/addon/filters/audio_decoder.o' failed
make[1]: *** [objs/addon/filters/audio_decoder.o] Error 1
make[1]: Leaving directory '/tmp/install.kaltura.sh/nginx-1.13.7'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by benzenesulfonic-acid** [comment]
Thank you for you help 
I change the os to debian 9.5 x64
Then I run 
prerequisites.sh in https://github.com/nebulabroadcast/nebula-setup
install.nginx.sh
install.ffmpeg.sh
Then run install.kaltura.sh but I meet the same problem ,
I fine it is the problem from ffmpeg (https://github.com/leandromoreira/ffmpeg-libav-tutorial/issues/29)
I change the gcc option flag remove the "-Werror" and try again 
Then I meet another problem 
![image](https://user-images.githubusercontent.com/36097692/46609822-9ea62e00-cb3b-11e8-8af6-53efd097ca93.png)
It seems I don't install HTTP Push Stream module. But the install.nginx.sh install it 
![image](https://user-images.githubusercontent.com/36097692/46610054-30ae3680-cb3c-11e8-8aec-a5185e047b19.png)

**Comment by sfahadshahzad** [comment]
Hi,

I am trying to run install.nginx got these error i am on Ubuntu 18.04 LTS.

cc1: all warnings being treated as errors
objs/Makefile:1499: recipe for target 'objs/addon/nginx-rtmp-module/ngx_rtmp_init.o' failed
make[1]: *** [objs/addon/nginx-rtmp-module/ngx_rtmp_init.o] Error 1
make[1]: Leaving directory '/tmp/install.nginx.sh/nginx-1.17.1'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by martastain** [comment]
We currently have the same problem on Debian Buster. I need to find some time and have a closer look. If you don't use rtmp, as a workaround you may just remove rtmp module from the REPOS list and delete rtmp section from nginx.conf

**Comment by sfahadshahzad** [comment]
just replace the rtmp module with https://github.com/arut/nginx-rtmp-module

Problem resolved

Thanks

**Comment by martastain** [comment]
I've fixed the problem in my fork, I've also merged kaltura and nginx installers, some modules are now optional and selectable using command line arguments. It will probably require more testing, but so far everything seems to be OK.
