### ISSUE TITLE
Could you add libvpx ??

### ISSUE THREAD

**Issue by reustaquiojr** [immstudios/installers#6]
Pls... Your script rullez... But we missing libvpx auto install !

**Comment by martastain** [comment]
Thanks!
I'll do it - it makes sense to have it. There's version 1.8.2 in Ubuntu 20.04 and 1.7.0 in Debian Buster. Do you think it is okay to use the repo version (which is the easiest way)? The latest is 1.10.0.

**Comment by martastain** [comment]
Added in https://github.com/immstudios/installers/commit/6394e564f50233a3bf05254771bdc29f949422d9 
Feel free to reopen this issue if it does not work correctly.
